/*
 * gen_sizeof.c
 * Introspects type sizes and generates a "Smart" H5_sizeof.h
 * * Logic:
 * 1. Prints C preprocessor code that checks for compiler-provided macros 
 * (e.g., __SIZEOF_INT__) first.
 * 2. Provides the runtime sizeof() check as a fallback default.
 * * This ensures correct sizes even if gen_sizeof runs on a build machine
 * different from the target (cross-compilation/universal binaries).
 */

#include <stdio.h>

/* --- Safe Header Inclusion for the Generator --- */
#if defined(__has_include) && __has_include(<stdint.h>)
    #include <stdint.h>
    #define HAVE_STDINT_H 1
#endif
#if defined(__has_include) && __has_include(<stdbool.h>)
    #include <stdbool.h>
    #define HAVE_STDBOOL_H 1
#endif
#if defined(__has_include) && __has_include(<stddef.h>)
    #include <stddef.h>
    #define HAVE_STDDEF_H 1
#endif
#if defined(__has_include) && __has_include(<time.h>)
    #include <time.h>
    #define HAVE_TIME_H 1
#endif
#if defined(__has_include) && __has_include(<sys/types.h>)
    #include <sys/types.h>
    #define HAVE_SYS_TYPES_H 1
#endif

/* Helper to print a smart size definition */
/* name: The HDF5 macro name (e.g., "H5_SIZEOF_INT")
 * compiler_macro: The GCC/Clang macro (e.g., "__SIZEOF_INT__")
 * fallback_val: The runtime sizeof() result to use if the macro is missing.
 */
void print_smart_size(const char *name, const char *compiler_macro, size_t fallback_val) {
    printf("#ifdef %s\n", compiler_macro);
    printf("    #define %s %s\n", name, compiler_macro);
    printf("#else\n");
    printf("    #define %s %zu\n", name, fallback_val);
    printf("#endif\n\n");
}

int is_little_endian(void) {
    int x = 1;
    return *(char *)&x;
}

int main(void) {
    printf("#ifndef H5_SIZEOF_H\n");
    printf("#define H5_SIZEOF_H\n\n");
    printf("/* Generated by gen_sizeof.c. \n");
    printf("   Prefers compiler macros (__SIZEOF_*) over runtime defaults. */\n\n");

    /* --- 1. Standard C Types (Compiler Macros available) --- */
    print_smart_size("H5_SIZEOF_CHAR",       "__SIZEOF_CHAR__",       sizeof(char));
    print_smart_size("H5_SIZEOF_SHORT",      "__SIZEOF_SHORT__",      sizeof(short));
    print_smart_size("H5_SIZEOF_INT",        "__SIZEOF_INT__",        sizeof(int));
    print_smart_size("H5_SIZEOF_LONG",       "__SIZEOF_LONG__",       sizeof(long));
    print_smart_size("H5_SIZEOF_LONG_LONG",  "__SIZEOF_LONG_LONG__",  sizeof(long long));
    print_smart_size("H5_SIZEOF_FLOAT",      "__SIZEOF_FLOAT__",      sizeof(float));
    print_smart_size("H5_SIZEOF_DOUBLE",     "__SIZEOF_DOUBLE__",     sizeof(double));
    print_smart_size("H5_SIZEOF_LONG_DOUBLE","__SIZEOF_LONG_DOUBLE__",sizeof(long double));
    print_smart_size("H5_SIZEOF_SIZE_T",     "__SIZEOF_SIZE_T__",     sizeof(size_t));
    print_smart_size("H5_SIZEOF_PTRDIFF_T",  "__SIZEOF_PTRDIFF_T__",  sizeof(ptrdiff_t));

    /* Unsigned is same size as int */
    print_smart_size("H5_SIZEOF_UNSIGNED",   "__SIZEOF_INT__",        sizeof(unsigned));

    /* --- 2. Boolean --- */
#ifdef HAVE_STDBOOL_H
    printf("#define H5_SIZEOF_BOOL %zu\n", sizeof(bool));
#else
    printf("#define H5_SIZEOF_BOOL 1\n");
#endif

    /* --- 3. Complex Types --- */
    /* Usually 2x the base float type. We calculate fallback at runtime. */
    printf("#define H5_SIZEOF_FLOAT_COMPLEX %zu\n", sizeof(float _Complex));
    printf("#define H5_SIZEOF_DOUBLE_COMPLEX %zu\n", sizeof(double _Complex));
    printf("#define H5_SIZEOF_LONG_DOUBLE_COMPLEX %zu\n", sizeof(long double _Complex));

    /* --- 4. System Types --- */
    
    /* time_t */
#ifdef HAVE_TIME_H
    printf("#define H5_SIZEOF_TIME_T %zu\n", sizeof(time_t));
#else
    printf("#define H5_SIZEOF_TIME_T 0\n");
#endif

    /* off_t */
#ifdef HAVE_SYS_TYPES_H
    printf("#define H5_SIZEOF_OFF_T %zu\n", sizeof(off_t));
    
    #if !defined(_MSC_VER)
        printf("#define H5_SIZEOF_SSIZE_T %zu\n", sizeof(ssize_t));
    #else
        printf("#define H5_SIZEOF_SSIZE_T 0\n");
    #endif
#else
    printf("#define H5_SIZEOF_OFF_T 0\n");
    printf("#define H5_SIZEOF_SSIZE_T 0\n");
#endif

    /* --- 5. stdint.h Types --- */
#ifdef HAVE_STDINT_H
    printf("\n/* stdint.h Types */\n");
    /* Fixed width types are defined by standard, so simple sizeof is usually safe,
       but being explicit costs nothing. */
    printf("#define H5_SIZEOF_INT8_T %zu\n", sizeof(int8_t));
    printf("#define H5_SIZEOF_UINT8_T %zu\n", sizeof(uint8_t));
    printf("#define H5_SIZEOF_INT16_T %zu\n", sizeof(int16_t));
    printf("#define H5_SIZEOF_UINT16_T %zu\n", sizeof(uint16_t));
    printf("#define H5_SIZEOF_INT32_T %zu\n", sizeof(int32_t));
    printf("#define H5_SIZEOF_UINT32_T %zu\n", sizeof(uint32_t));
    printf("#define H5_SIZEOF_INT64_T %zu\n", sizeof(int64_t));
    printf("#define H5_SIZEOF_UINT64_T %zu\n", sizeof(uint64_t));

    /* Fast/Least types are tricky and platform dependent */
    printf("#define H5_SIZEOF_INT_FAST8_T %zu\n", sizeof(int_fast8_t));
    printf("#define H5_SIZEOF_UINT_FAST8_T %zu\n", sizeof(uint_fast8_t));
    printf("#define H5_SIZEOF_INT_FAST16_T %zu\n", sizeof(int_fast16_t));
    printf("#define H5_SIZEOF_UINT_FAST16_T %zu\n", sizeof(uint_fast16_t));
    printf("#define H5_SIZEOF_INT_FAST32_T %zu\n", sizeof(int_fast32_t));
    printf("#define H5_SIZEOF_UINT_FAST32_T %zu\n", sizeof(uint_fast32_t));
    printf("#define H5_SIZEOF_INT_FAST64_T %zu\n", sizeof(int_fast64_t));
    printf("#define H5_SIZEOF_UINT_FAST64_T %zu\n", sizeof(uint_fast64_t));

    printf("#define H5_SIZEOF_INT_LEAST8_T %zu\n", sizeof(int_least8_t));
    printf("#define H5_SIZEOF_UINT_LEAST8_T %zu\n", sizeof(uint_least8_t));
    printf("#define H5_SIZEOF_INT_LEAST16_T %zu\n", sizeof(int_least16_t));
    printf("#define H5_SIZEOF_UINT_LEAST16_T %zu\n", sizeof(uint_least16_t));
    printf("#define H5_SIZEOF_INT_LEAST32_T %zu\n", sizeof(int_least32_t));
    printf("#define H5_SIZEOF_UINT_LEAST32_T %zu\n", sizeof(uint_least32_t));
    printf("#define H5_SIZEOF_INT_LEAST64_T %zu\n", sizeof(int_least64_t));
    printf("#define H5_SIZEOF_UINT_LEAST64_T %zu\n", sizeof(uint_least64_t));
#endif

    /* --- 6. Feature Detection: _Float16 --- */
    /* Always defer to compiler macro for this non-standard type */
    printf("\n#if defined(__FLT16_MAX__) || defined(__FLT16_MANT_DIG__)\n");
    printf("    #define H5_SIZEOF__FLOAT16 2\n");
    printf("#else\n");
    printf("    #define H5_SIZEOF__FLOAT16 0\n");
    printf("#endif\n");

    /* --- 7. Endianness --- */
    /* "Smart" Logic: Check compiler macros first, then fall back to gen_sizeof result */
    printf("\n/* Endianness Detection */\n");
    printf("#if defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__) && \\\n");
    printf("    __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__\n");
    printf("    #define WORDS_BIGENDIAN 1\n");
    printf("#elif defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && \\\n");
    printf("    __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__\n");
    printf("    #undef WORDS_BIGENDIAN\n");
    printf("#else\n");
    /* Fallback to what we detected at runtime */
    if (is_little_endian()) {
        printf("    #undef WORDS_BIGENDIAN\n");
    } else {
        printf("    #define WORDS_BIGENDIAN 1\n");
    }
    printf("#endif\n");

    printf("\n#endif /* H5_SIZEOF_H */\n");
    return 0;
}