#ifndef H5_PUBCONF_H
#define H5_PUBCONF_H

/* ========================================================================== */
/* 1. Runtime / Generator Definitions & Overrides                           */
/* ========================================================================== */
/* Expects H5_SIZEOF_* macros and Endianness definitions from gen_config.c */
#include "H5_sizeof.h"

/* Compiler Override Strategy:
 * If the compiler defines standard size macros (GCC/Clang), prefer those
 * over the runtime values generated by gen_sizeof.c
 */
#ifdef __SIZEOF_CHAR__
    #undef H5_SIZEOF_CHAR
    #define H5_SIZEOF_CHAR __SIZEOF_CHAR__
#endif
#ifdef __SIZEOF_SHORT__
    #undef H5_SIZEOF_SHORT
    #define H5_SIZEOF_SHORT __SIZEOF_SHORT__
#endif
#ifdef __SIZEOF_INT__
    #undef H5_SIZEOF_INT
    #define H5_SIZEOF_INT __SIZEOF_INT__
    #undef H5_SIZEOF_UNSIGNED
    #define H5_SIZEOF_UNSIGNED __SIZEOF_INT__
#endif
#ifdef __SIZEOF_LONG__
    #undef H5_SIZEOF_LONG
    #define H5_SIZEOF_LONG __SIZEOF_LONG__
#endif
#ifdef __SIZEOF_LONG_LONG__
    #undef H5_SIZEOF_LONG_LONG
    #define H5_SIZEOF_LONG_LONG __SIZEOF_LONG_LONG__
#endif
#ifdef __SIZEOF_FLOAT__
    #undef H5_SIZEOF_FLOAT
    #define H5_SIZEOF_FLOAT __SIZEOF_FLOAT__
#endif
#ifdef __SIZEOF_DOUBLE__
    #undef H5_SIZEOF_DOUBLE
    #define H5_SIZEOF_DOUBLE __SIZEOF_DOUBLE__
#endif
#ifdef __SIZEOF_LONG_DOUBLE__
    #undef H5_SIZEOF_LONG_DOUBLE
    #define H5_SIZEOF_LONG_DOUBLE __SIZEOF_LONG_DOUBLE__
#endif
#ifdef __SIZEOF_SIZE_T__
    #undef H5_SIZEOF_SIZE_T
    #define H5_SIZEOF_SIZE_T __SIZEOF_SIZE_T__
#endif
#ifdef __SIZEOF_PTRDIFF_T__
    #undef H5_SIZEOF_PTRDIFF_T
    #define H5_SIZEOF_PTRDIFF_T __SIZEOF_PTRDIFF_T__
#endif

/* Endianness Override */
#ifdef __BYTE_ORDER__
    #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
        #undef WORDS_BIGENDIAN
    #elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
        #undef WORDS_BIGENDIAN
        #define WORDS_BIGENDIAN 1
    #endif
#endif
#ifdef __BIG_ENDIAN__
  #define WORDS_BIGENDIAN 1
#endif


/* ========================================================================== */
/* 2. Project Metadata & Policy                                             */
/* ========================================================================== */
#define H5_PACKAGE_NAME "HDF5"
#define H5_PACKAGE_VERSION "2.0.0"
#define H5_PACKAGE_STRING "HDF5 2.0.0"
#define H5_PACKAGE_BUGREPORT "help@hdfgroup.org"
#define H5_PACKAGE "hdf5"
#define H5_PACKAGE_TARNAME "hdf5"
#define H5_PACKAGE_URL "https://www.hdfgroup.org"
#define H5_VERSION "2.0.0"

#define H5_USE_FILE_LOCKING 1
#define H5_IGNORE_DISABLED_FILE_LOCKS 1
#define H5_HAVE_EMBEDDED_LIBINFO 1
#define H5_WANT_DATA_ACCURACY 1
#define H5_WANT_DCONV_EXCEPTION 1
#define H5_INCLUDE_HL 1


/* ========================================================================== */
/* 3. Compiler & Feature Detection                                          */
/* ========================================================================== */
#if !defined(__has_include)
    #error "Your compiler is too old to build this package. GCC >= 5.0 or Clang >= 3.0 is required."
#endif

#define H5_HAVE_ATTRIBUTE 1
#define H5_HAVE_C99_COMPLEX_NUMBERS 1
#define H5_HAVE_COMPLEX_NUMBERS 1
#define H5_STDC_HEADERS 1
#define H5_HAVE_IEEE_754 1

#ifdef __SIZEOF_FLOAT128__
    #define H5_HAVE_FLOAT128 1
#endif


/* ========================================================================== */
/* 4. Filter & Compression Support                                          */
/* ========================================================================== */
#define H5_HAVE_FILTER_DEFLATE 1
#define H5_HAVE_ZLIB_H 1
#define H5_HAVE_LIBZ 1
#define H5_HAVE_LIBM 1


/* ========================================================================== */
/* 5. Header-Based Feature Detection                                        */
/* ========================================================================== */
/* Note: We liberally enable features here if the header exists.
   We then explicitly UNDEF them in the Windows section if they are broken. */

/* --- Threading --- */
#if __has_include(<pthread.h>)
    #define H5_HAVE_PTHREAD_H 1
    #define H5_HAVE_THREADSAFE 1
    #define H5_HAVE_THREADS 1
    #define H5_HAVE_CONCURRENCY 1
#endif

#if __has_include(<stdatomic.h>)
    #define H5_HAVE_STDATOMIC_H 1
#endif

/* --- System Headers & Features --- */

#if __has_include(<unistd.h>)
    #define H5_HAVE_UNISTD_H 1
    #define H5_HAVE_ALARM 1
    #define H5_HAVE_FORK 1
    #define H5_HAVE_GETHOSTNAME 1
    #define H5_HAVE_SYMLINK 1
    #define H5_HAVE_PREADWRITE 1
#endif

#if __has_include(<fcntl.h>)
    #define H5_HAVE_FCNTL 1 
#endif

#if __has_include(<sys/types.h>)
    #define H5_HAVE_SYS_TYPES_H 1
#endif

#if __has_include(<sys/stat.h>)
    #define H5_HAVE_SYS_STAT_H 1
    #define H5_HAVE_STAT_ST_BLOCKS 1
#endif

#if __has_include(<sys/wait.h>)
    #define H5_HAVE_SYS_WAIT_H 1
    #define H5_HAVE_WAITPID 1
#endif

#if __has_include(<sys/file.h>)
    #define H5_HAVE_SYS_FILE_H 1
    #define H5_HAVE_FLOCK 1
#endif

#if __has_include(<sys/time.h>)
    #define H5_HAVE_SYS_TIME_H 1
    #define H5_HAVE_GETTIMEOFDAY 1
#endif

#if __has_include(<sys/resource.h>)
    #define H5_HAVE_SYS_RESOURCE_H 1
    #define H5_HAVE_GETRUSAGE 1
#endif

#if __has_include(<sys/ioctl.h>)
    #define H5_HAVE_SYS_IOCTL_H 1
    #define H5_HAVE_IOCTL 1
    #define H5_HAVE_TIOCGETD 1
    #define H5_HAVE_TIOCGWINSZ 1
#endif

#if __has_include(<sys/socket.h>)
    #define H5_HAVE_SYS_SOCKET_H 1
#endif

#if __has_include(<io.h>)
    #define H5_HAVE_IO_H 1
#endif

#if __has_include(<dirent.h>)
    #define H5_HAVE_DIRENT_H 1
#endif

#if __has_include(<dlfcn.h>)
    #define H5_HAVE_DLFCN_H 1
    #define H5_HAVE_LIBDL 1
#endif

#if __has_include(<pwd.h>)
    #define H5_HAVE_PWD_H 1
#endif

#if __has_include(<netdb.h>)
    #define H5_HAVE_NETDB_H 1
#endif

#if __has_include(<arpa/inet.h>)
    #define H5_HAVE_ARPA_INET_H 1
#endif

#if __has_include(<netinet/in.h>)
    #define H5_HAVE_NETINET_IN_H 1
#endif

#if __has_include(<time.h>)
    #define H5_HAVE_TIME_H 1
    #define H5_HAVE_TIMEZONE 1
    #define H5_HAVE_TM_GMTOFF 1
    #define H5_HAVE_CLOCK_GETTIME 1
#endif

#if __has_include(<string.h>)
    #define H5_HAVE_STRDUP 1
    #define H5_HAVE_STRCASESTR 1
#endif

#if __has_include(<stdio.h>)
    #define H5_HAVE_TMPFILE 1
    #define H5_HAVE_ASPRINTF
    #define H5_HAVE_VASPRINTF
#endif

#if __has_include(<stdlib.h>)
    #define H5_HAVE_QSORT_REENTRANT 1
#endif


/* ========================================================================== */
/* 6. Platform Specifics (Overrides & Exceptions)                           */
/* ========================================================================== */

/* --- Windows Specifics (Rtools / MinGW) --- */
#if defined(_WIN32) || defined(__MINGW32__)
    #define H5_HAVE_WINDOWS 1
    #define H5_HAVE_WIN32_API 1
    #define H5_HAVE_MINGW 1
    #define H5_HAVE_LIBWS2_32 1
    #define H5_HAVE_WINDOW_PATH 1
    #define H5_HAVE_GETCONSOLESCREENBUFFERINFO 1
    #define H5_DEFAULT_PLUGINDIR "%ALLUSERSPROFILE%\\hdf5\\lib\\plugin"
    
    /* * Windows Exception List *
     * The following features may have headers present on MinGW, but the
     * functionality is broken, unsupported, or causes conflict with HDF5.
     */

    /* Threading: Use Pthreads (already enabled above), explicit deny Win32 threads */
    #undef H5_HAVE_WIN_THREADS

    /* File I/O & Locking: MinGW has headers but lacks struct flock or correct fcntl behavior */
    #undef H5_HAVE_FCNTL
    #undef H5_HAVE_FLOCK
    #undef H5_HAVE_SYMLINK
    #undef H5_HAVE_PREADWRITE

    /* String/Time/System: Missing GNU/BSD extensions on Windows */
    #undef H5_HAVE_STRCASESTR
    #undef H5_HAVE_TM_GMTOFF
    #undef H5_HAVE_GETRUSAGE
    #undef H5_HAVE_QSORT_REENTRANT

    /* IOCTL: MinGW headers might exist but HDF5 logic often fails on Windows IOCTLs */
    #undef H5_HAVE_IOCTL
    #undef H5_HAVE_TIOCGETD
    #undef H5_HAVE_TIOCGWINSZ
    #undef H5_HAVE_SYS_IOCTL_H

/* --- POSIX Specifics (Linux / macOS / BSD) --- */
#else
    #define H5_DEFAULT_PLUGINDIR "/usr/local/hdf5/lib/plugin"
    
    #if defined(__APPLE__)
        #define H5_HAVE_DARWIN 1
    #endif
#endif


/* ========================================================================== */
/* 7. Disable GNU Extensions and other non-Portable functions.                */
/* ========================================================================== */

/* --- String Handling --- */
/* Force standard C string functions. 
   Disable extensions like strcasestr, asprintf, vasprintf to ensure 
   portability without _GNU_SOURCE. */
#undef H5_HAVE_STRCASESTR
#undef H5_HAVE_ASPRINTF
#undef H5_HAVE_VASPRINTF

/* --- Sorting --- */
/* Disable qsort_r because signatures differ between GNU and BSD/macOS */
#undef H5_HAVE_QSORT_REENTRANT

/* --- Time & Date --- */
/* Rely on standard time functions, avoiding BSD/SysV extensions */
#undef H5_HAVE_TM_GMTOFF
#undef H5_HAVE_TIMEZONE
#undef H5_HAVE_STRUCT_TIMEZONE

/* --- System / IOCTL --- */
/* Disable terminal IOCTLs (not needed for library usage) */
#undef H5_HAVE_IOCTL
#undef H5_HAVE_TIOCGETD
#undef H5_HAVE_TIOCGWINSZ
#undef H5_HAVE_GETCONSOLESCREENBUFFERINFO


#endif /* H5_PUBCONF_H */
