/*
 * query_byte_widths.c
 * Introspects type sizes for HDF5 configuration (R Package Build).
 *
 * This generator outputs the "Default" sizes based on the machine performing
 * the build. These definitions are intended to be included by H5pubconf.h,
 * which may override them using compiler macros (e.g. __SIZEOF_INT__) to
 * support cross-compilation or universal binary builds.
 */

#include <stdio.h>

/* --- Safe Header Inclusion --- */
#if defined(__has_include) && __has_include(<stdint.h>)
    #include <stdint.h>
    #define HAVE_STDINT_H 1
#endif
#if defined(__has_include) && __has_include(<stdbool.h>)
    #include <stdbool.h>
    #define HAVE_STDBOOL_H 1
#endif
#if defined(__has_include) && __has_include(<stddef.h>)
    #include <stddef.h>
    #define HAVE_STDDEF_H 1
#endif
#if defined(__has_include) && __has_include(<time.h>)
    #include <time.h>
    #define HAVE_TIME_H 1
#endif
#if defined(__has_include) && __has_include(<sys/types.h>)
    #include <sys/types.h>
    #define HAVE_SYS_TYPES_H 1
#endif

/* Helper to detect endianness at runtime */
int is_little_endian(void) {
    int x = 1;
    return *(char *)&x;
}

int main(void) {
    printf("#ifndef H5_BYTE_WIDTHS_H\n");
    printf("#define H5_BYTE_WIDTHS_H\n\n");
    printf("/* Generated by query_byte_widths.c */\n\n");

    /* 1. Standard C Integers */
    printf("#define H5_SIZEOF_CHAR %zu\n", sizeof(char));
    printf("#define H5_SIZEOF_SHORT %zu\n", sizeof(short));
    printf("#define H5_SIZEOF_INT %zu\n", sizeof(int));
    printf("#define H5_SIZEOF_UNSIGNED %zu\n", sizeof(unsigned));
    printf("#define H5_SIZEOF_LONG %zu\n", sizeof(long));
    printf("#define H5_SIZEOF_LONG_LONG %zu\n", sizeof(long long));
    
    /* 2. Floating Point */
    printf("#define H5_SIZEOF_FLOAT %zu\n", sizeof(float));
    printf("#define H5_SIZEOF_DOUBLE %zu\n", sizeof(double));
    printf("#define H5_SIZEOF_LONG_DOUBLE %zu\n", sizeof(long double));

    /* 3. C99 Complex Types */
    printf("#define H5_SIZEOF_FLOAT_COMPLEX %zu\n", sizeof(float _Complex));
    printf("#define H5_SIZEOF_DOUBLE_COMPLEX %zu\n", sizeof(double _Complex));
    printf("#define H5_SIZEOF_LONG_DOUBLE_COMPLEX %zu\n", sizeof(long double _Complex));

    /* 4. Boolean */
#ifdef HAVE_STDBOOL_H
    printf("#define H5_SIZEOF_BOOL %zu\n", sizeof(bool));
#else
    printf("#define H5_SIZEOF_BOOL 1\n");
#endif

    /* 5. System Types */
#ifdef HAVE_STDDEF_H
    printf("#define H5_SIZEOF_SIZE_T %zu\n", sizeof(size_t));
    printf("#define H5_SIZEOF_PTRDIFF_T %zu\n", sizeof(ptrdiff_t));
#else
    printf("#define H5_SIZEOF_SIZE_T %zu\n", sizeof(long));
    printf("#define H5_SIZEOF_PTRDIFF_T %zu\n", sizeof(long));
#endif

#ifdef HAVE_TIME_H
    printf("#define H5_SIZEOF_TIME_T %zu\n", sizeof(time_t));
#else
    printf("#define H5_SIZEOF_TIME_T 0\n");
#endif

    /* 6. POSIX Types */
#ifdef HAVE_SYS_TYPES_H
    printf("#define H5_SIZEOF_OFF_T %zu\n", sizeof(off_t));
    #if !defined(_MSC_VER)
        printf("#define H5_SIZEOF_SSIZE_T %zu\n", sizeof(ssize_t));
    #else
        printf("#define H5_SIZEOF_SSIZE_T 0\n");
    #endif
#else
    printf("#define H5_SIZEOF_OFF_T 0\n");
    printf("#define H5_SIZEOF_SSIZE_T 0\n");
#endif

    /* 7. stdint.h Types */
#ifdef HAVE_STDINT_H
    printf("#define H5_SIZEOF_INT8_T %zu\n", sizeof(int8_t));
    printf("#define H5_SIZEOF_UINT8_T %zu\n", sizeof(uint8_t));
    printf("#define H5_SIZEOF_INT16_T %zu\n", sizeof(int16_t));
    printf("#define H5_SIZEOF_UINT16_T %zu\n", sizeof(uint16_t));
    printf("#define H5_SIZEOF_INT32_T %zu\n", sizeof(int32_t));
    printf("#define H5_SIZEOF_UINT32_T %zu\n", sizeof(uint32_t));
    printf("#define H5_SIZEOF_INT64_T %zu\n", sizeof(int64_t));
    printf("#define H5_SIZEOF_UINT64_T %zu\n", sizeof(uint64_t));

    printf("#define H5_SIZEOF_INT_FAST8_T %zu\n", sizeof(int_fast8_t));
    printf("#define H5_SIZEOF_UINT_FAST8_T %zu\n", sizeof(uint_fast8_t));
    printf("#define H5_SIZEOF_INT_FAST16_T %zu\n", sizeof(int_fast16_t));
    printf("#define H5_SIZEOF_UINT_FAST16_T %zu\n", sizeof(uint_fast16_t));
    printf("#define H5_SIZEOF_INT_FAST32_T %zu\n", sizeof(int_fast32_t));
    printf("#define H5_SIZEOF_UINT_FAST32_T %zu\n", sizeof(uint_fast32_t));
    printf("#define H5_SIZEOF_INT_FAST64_T %zu\n", sizeof(int_fast64_t));
    printf("#define H5_SIZEOF_UINT_FAST64_T %zu\n", sizeof(uint_fast64_t));

    printf("#define H5_SIZEOF_INT_LEAST8_T %zu\n", sizeof(int_least8_t));
    printf("#define H5_SIZEOF_UINT_LEAST8_T %zu\n", sizeof(uint_least8_t));
    printf("#define H5_SIZEOF_INT_LEAST16_T %zu\n", sizeof(int_least16_t));
    printf("#define H5_SIZEOF_UINT_LEAST16_T %zu\n", sizeof(uint_least16_t));
    printf("#define H5_SIZEOF_INT_LEAST32_T %zu\n", sizeof(int_least32_t));
    printf("#define H5_SIZEOF_UINT_LEAST32_T %zu\n", sizeof(uint_least32_t));
    printf("#define H5_SIZEOF_INT_LEAST64_T %zu\n", sizeof(int_least64_t));
    printf("#define H5_SIZEOF_UINT_LEAST64_T %zu\n", sizeof(uint_least64_t));
#endif

    /* 8. Feature Detection: _Float16 */
#if defined(__FLT16_MAX__) || defined(__FLT16_MANT_DIG__)
    printf("#define H5_SIZEOF__FLOAT16 %zu\n", sizeof(_Float16));
#else
    printf("#define H5_SIZEOF__FLOAT16 0\n");
#endif

    /* 9. Endianness (Runtime Default) */
    if (is_little_endian()) {
        printf("#undef WORDS_BIGENDIAN\n");
    } else {
        printf("#define WORDS_BIGENDIAN 1\n");
    }

    printf("\n#endif /* H5_BYTE_WIDTHS_H */\n");
    return 0;
}
